// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: quiz/gunk/v1/quiz/all.proto

package quizpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CategoryID int32  `protobuf:"varint,2,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	QuizTitle  string `protobuf:"bytes,3,opt,name=QuizTitle,proto3" json:"QuizTitle,omitempty"`
	QuizTime   int32  `protobuf:"varint,4,opt,name=QuizTime,proto3" json:"QuizTime,omitempty"`
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Quiz) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *Quiz) GetQuizTitle() string {
	if x != nil {
		return x.QuizTitle
	}
	return ""
}

func (x *Quiz) GetQuizTime() int32 {
	if x != nil {
		return x.QuizTime
	}
	return 0
}

type ListQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CategoryName string `protobuf:"bytes,2,opt,name=CategoryName,proto3" json:"CategoryName,omitempty"`
	QuizTitle    string `protobuf:"bytes,3,opt,name=QuizTitle,proto3" json:"QuizTitle,omitempty"`
}

func (x *ListQuiz) Reset() {
	*x = ListQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuiz) ProtoMessage() {}

func (x *ListQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuiz.ProtoReflect.Descriptor instead.
func (*ListQuiz) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{1}
}

func (x *ListQuiz) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ListQuiz) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ListQuiz) GetQuizTitle() string {
	if x != nil {
		return x.QuizTitle
	}
	return ""
}

type QuizFilterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalQuiz  []*ListQuiz `protobuf:"bytes,1,rep,name=TotalQuiz,proto3" json:"TotalQuiz,omitempty"`
	SearchTerm string      `protobuf:"bytes,2,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
}

func (x *QuizFilterList) Reset() {
	*x = QuizFilterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizFilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizFilterList) ProtoMessage() {}

func (x *QuizFilterList) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizFilterList.ProtoReflect.Descriptor instead.
func (*QuizFilterList) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{2}
}

func (x *QuizFilterList) GetTotalQuiz() []*ListQuiz {
	if x != nil {
		return x.TotalQuiz
	}
	return nil
}

func (x *QuizFilterList) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchTerm string `protobuf:"bytes,1,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
}

func (x *ListQuizRequest) Reset() {
	*x = ListQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuizRequest) ProtoMessage() {}

func (x *ListQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuizRequest.ProtoReflect.Descriptor instead.
func (*ListQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{3}
}

func (x *ListQuizRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizFilterList *QuizFilterList `protobuf:"bytes,1,opt,name=QuizFilterList,proto3" json:"QuizFilterList,omitempty"`
}

func (x *ListQuizResponse) Reset() {
	*x = ListQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuizResponse) ProtoMessage() {}

func (x *ListQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuizResponse.ProtoReflect.Descriptor instead.
func (*ListQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{4}
}

func (x *ListQuizResponse) GetQuizFilterList() *QuizFilterList {
	if x != nil {
		return x.QuizFilterList
	}
	return nil
}

type CreateQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CategoryID int32  `protobuf:"varint,2,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	QuizTitle  string `protobuf:"bytes,3,opt,name=QuizTitle,proto3" json:"QuizTitle,omitempty"`
	QuizTime   int32  `protobuf:"varint,4,opt,name=QuizTime,proto3" json:"QuizTime,omitempty"`
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{5}
}

func (x *CreateQuizRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *CreateQuizRequest) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *CreateQuizRequest) GetQuizTitle() string {
	if x != nil {
		return x.QuizTitle
	}
	return ""
}

func (x *CreateQuizRequest) GetQuizTime() int32 {
	if x != nil {
		return x.QuizTime
	}
	return 0
}

type CreateQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quiz *Quiz `protobuf:"bytes,1,opt,name=Quiz,proto3" json:"Quiz,omitempty"`
}

func (x *CreateQuizResponse) Reset() {
	*x = CreateQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizResponse) ProtoMessage() {}

func (x *CreateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizResponse.ProtoReflect.Descriptor instead.
func (*CreateQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{6}
}

func (x *CreateQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type DeleteQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteQuizRequest) Reset() {
	*x = DeleteQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizRequest) ProtoMessage() {}

func (x *DeleteQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteQuizRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQuizResponse) Reset() {
	*x = DeleteQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuizResponse) ProtoMessage() {}

func (x *DeleteQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuizResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{8}
}

type EditQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *EditQuizRequest) Reset() {
	*x = EditQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditQuizRequest) ProtoMessage() {}

func (x *EditQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditQuizRequest.ProtoReflect.Descriptor instead.
func (*EditQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{9}
}

func (x *EditQuizRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type EditQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quiz *Quiz `protobuf:"bytes,1,opt,name=Quiz,proto3" json:"Quiz,omitempty"`
}

func (x *EditQuizResponse) Reset() {
	*x = EditQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditQuizResponse) ProtoMessage() {}

func (x *EditQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditQuizResponse.ProtoReflect.Descriptor instead.
func (*EditQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{10}
}

func (x *EditQuizResponse) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

type UpdateQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CategoryID int32  `protobuf:"varint,2,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	QuizTitle  string `protobuf:"bytes,3,opt,name=QuizTitle,proto3" json:"QuizTitle,omitempty"`
	QuizTime   int32  `protobuf:"varint,4,opt,name=QuizTime,proto3" json:"QuizTime,omitempty"`
}

func (x *UpdateQuizRequest) Reset() {
	*x = UpdateQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizRequest) ProtoMessage() {}

func (x *UpdateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateQuizRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateQuizRequest) GetCategoryID() int32 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *UpdateQuizRequest) GetQuizTitle() string {
	if x != nil {
		return x.QuizTitle
	}
	return ""
}

func (x *UpdateQuizRequest) GetQuizTime() int32 {
	if x != nil {
		return x.QuizTime
	}
	return 0
}

type UpdateQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateQuizResponse) Reset() {
	*x = UpdateQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuizResponse) ProtoMessage() {}

func (x *UpdateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_quiz_all_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuizResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP(), []int{12}
}

var File_quiz_gunk_v1_quiz_all_proto protoreflect.FileDescriptor

var file_quiz_gunk_v1_quiz_all_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x71,
	0x75, 0x69, 0x7a, 0x2f, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x71,
	0x75, 0x69, 0x7a, 0x70, 0x62, 0x22, 0x83, 0x01, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x16,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1d, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28,
	0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1c, 0x0a, 0x08, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x6b, 0x0a, 0x08, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12,
	0x20, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50,
	0x00, 0x12, 0x1d, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00,
	0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x69, 0x0a, 0x0e, 0x51, 0x75, 0x69, 0x7a,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x09, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x51, 0x75, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10,
	0x00, 0x18, 0x00, 0x22, 0x39, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x54, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x56,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x51, 0x75, 0x69, 0x7a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x71, 0x75, 0x69,
	0x7a, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06,
	0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x90, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x12, 0x1d, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x12, 0x1c, 0x0a, 0x08, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50,
	0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22,
	0x33, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00,
	0x10, 0x00, 0x18, 0x00, 0x22, 0x1c, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75,
	0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00,
	0x18, 0x00, 0x22, 0x31, 0x0a, 0x0f, 0x45, 0x64, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08,
	0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x42, 0x0a, 0x10, 0x45, 0x64, 0x69, 0x74, 0x51, 0x75, 0x69,
	0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x51, 0x75, 0x69,
	0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62,
	0x2e, 0x51, 0x75, 0x69, 0x7a, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50,
	0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x90, 0x01, 0x0a, 0x11, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1d, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x7a, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1c, 0x0a, 0x08, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x1c, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x32, 0x9b, 0x03, 0x0a, 0x0b, 0x51,
	0x75, 0x69, 0x7a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x19, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x19, 0x2e, 0x71, 0x75, 0x69, 0x7a,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x49, 0x0a, 0x08,
	0x45, 0x64, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x17, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70,
	0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x51,
	0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00,
	0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x19, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02,
	0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x49, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74,
	0x51, 0x75, 0x69, 0x7a, 0x12, 0x17, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28,
	0x00, 0x30, 0x00, 0x1a, 0x03, 0x88, 0x02, 0x00, 0x42, 0x33, 0x48, 0x01, 0x50, 0x00, 0x5a, 0x18,
	0x71, 0x75, 0x69, 0x7a, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x69,
	0x7a, 0x3b, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x80, 0x01, 0x00, 0x88, 0x01, 0x00, 0x90, 0x01,
	0x00, 0xb8, 0x01, 0x00, 0xd8, 0x01, 0x00, 0xf8, 0x01, 0x01, 0xd0, 0x02, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quiz_gunk_v1_quiz_all_proto_rawDescOnce sync.Once
	file_quiz_gunk_v1_quiz_all_proto_rawDescData = file_quiz_gunk_v1_quiz_all_proto_rawDesc
)

func file_quiz_gunk_v1_quiz_all_proto_rawDescGZIP() []byte {
	file_quiz_gunk_v1_quiz_all_proto_rawDescOnce.Do(func() {
		file_quiz_gunk_v1_quiz_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_quiz_gunk_v1_quiz_all_proto_rawDescData)
	})
	return file_quiz_gunk_v1_quiz_all_proto_rawDescData
}

var (
	file_quiz_gunk_v1_quiz_all_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
	file_quiz_gunk_v1_quiz_all_proto_goTypes  = []interface{}{
		(*Quiz)(nil),               // 0: quizpb.Quiz
		(*ListQuiz)(nil),           // 1: quizpb.ListQuiz
		(*QuizFilterList)(nil),     // 2: quizpb.QuizFilterList
		(*ListQuizRequest)(nil),    // 3: quizpb.ListQuizRequest
		(*ListQuizResponse)(nil),   // 4: quizpb.ListQuizResponse
		(*CreateQuizRequest)(nil),  // 5: quizpb.CreateQuizRequest
		(*CreateQuizResponse)(nil), // 6: quizpb.CreateQuizResponse
		(*DeleteQuizRequest)(nil),  // 7: quizpb.DeleteQuizRequest
		(*DeleteQuizResponse)(nil), // 8: quizpb.DeleteQuizResponse
		(*EditQuizRequest)(nil),    // 9: quizpb.EditQuizRequest
		(*EditQuizResponse)(nil),   // 10: quizpb.EditQuizResponse
		(*UpdateQuizRequest)(nil),  // 11: quizpb.UpdateQuizRequest
		(*UpdateQuizResponse)(nil), // 12: quizpb.UpdateQuizResponse
	}
)

var file_quiz_gunk_v1_quiz_all_proto_depIdxs = []int32{
	1,  // 0: quizpb.QuizFilterList.TotalQuiz:type_name -> quizpb.ListQuiz
	2,  // 1: quizpb.ListQuizResponse.QuizFilterList:type_name -> quizpb.QuizFilterList
	0,  // 2: quizpb.CreateQuizResponse.Quiz:type_name -> quizpb.Quiz
	0,  // 3: quizpb.EditQuizResponse.Quiz:type_name -> quizpb.Quiz
	5,  // 4: quizpb.QuizService.CreateQuiz:input_type -> quizpb.CreateQuizRequest
	7,  // 5: quizpb.QuizService.DeleteQuiz:input_type -> quizpb.DeleteQuizRequest
	9,  // 6: quizpb.QuizService.EditQuiz:input_type -> quizpb.EditQuizRequest
	11, // 7: quizpb.QuizService.UpdateQuiz:input_type -> quizpb.UpdateQuizRequest
	3,  // 8: quizpb.QuizService.ListQuiz:input_type -> quizpb.ListQuizRequest
	6,  // 9: quizpb.QuizService.CreateQuiz:output_type -> quizpb.CreateQuizResponse
	8,  // 10: quizpb.QuizService.DeleteQuiz:output_type -> quizpb.DeleteQuizResponse
	10, // 11: quizpb.QuizService.EditQuiz:output_type -> quizpb.EditQuizResponse
	12, // 12: quizpb.QuizService.UpdateQuiz:output_type -> quizpb.UpdateQuizResponse
	4,  // 13: quizpb.QuizService.ListQuiz:output_type -> quizpb.ListQuizResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_quiz_gunk_v1_quiz_all_proto_init() }
func file_quiz_gunk_v1_quiz_all_proto_init() {
	if File_quiz_gunk_v1_quiz_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuizFilterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_quiz_all_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quiz_gunk_v1_quiz_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_gunk_v1_quiz_all_proto_goTypes,
		DependencyIndexes: file_quiz_gunk_v1_quiz_all_proto_depIdxs,
		MessageInfos:      file_quiz_gunk_v1_quiz_all_proto_msgTypes,
	}.Build()
	File_quiz_gunk_v1_quiz_all_proto = out.File
	file_quiz_gunk_v1_quiz_all_proto_rawDesc = nil
	file_quiz_gunk_v1_quiz_all_proto_goTypes = nil
	file_quiz_gunk_v1_quiz_all_proto_depIdxs = nil
}
