// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: quiz/gunk/v1/option/all.proto

package optionpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	QuestionID int32  `protobuf:"varint,2,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"`
	OptionName string `protobuf:"bytes,3,opt,name=OptionName,proto3" json:"OptionName,omitempty"`
	IsCorrect  bool   `protobuf:"varint,4,opt,name=IsCorrect,proto3" json:"IsCorrect,omitempty"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Option) GetQuestionID() int32 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

func (x *Option) GetOptionName() string {
	if x != nil {
		return x.OptionName
	}
	return ""
}

func (x *Option) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type OptionFilterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalOption []*Option `protobuf:"bytes,1,rep,name=TotalOption,proto3" json:"TotalOption,omitempty"`
	SearchTerm  string    `protobuf:"bytes,2,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
}

func (x *OptionFilterList) Reset() {
	*x = OptionFilterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionFilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionFilterList) ProtoMessage() {}

func (x *OptionFilterList) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionFilterList.ProtoReflect.Descriptor instead.
func (*OptionFilterList) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{1}
}

func (x *OptionFilterList) GetTotalOption() []*Option {
	if x != nil {
		return x.TotalOption
	}
	return nil
}

func (x *OptionFilterList) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchTerm string `protobuf:"bytes,1,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
}

func (x *ListOptionRequest) Reset() {
	*x = ListOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionRequest) ProtoMessage() {}

func (x *ListOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionRequest.ProtoReflect.Descriptor instead.
func (*ListOptionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{2}
}

func (x *ListOptionRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionFilterList *OptionFilterList `protobuf:"bytes,1,opt,name=OptionFilterList,proto3" json:"OptionFilterList,omitempty"`
}

func (x *ListOptionResponse) Reset() {
	*x = ListOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionResponse) ProtoMessage() {}

func (x *ListOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionResponse.ProtoReflect.Descriptor instead.
func (*ListOptionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{3}
}

func (x *ListOptionResponse) GetOptionFilterList() *OptionFilterList {
	if x != nil {
		return x.OptionFilterList
	}
	return nil
}

type CreateOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	QuestionID int32  `protobuf:"varint,2,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"`
	OptionName string `protobuf:"bytes,3,opt,name=OptionName,proto3" json:"OptionName,omitempty"`
}

func (x *CreateOptionRequest) Reset() {
	*x = CreateOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOptionRequest) ProtoMessage() {}

func (x *CreateOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOptionRequest.ProtoReflect.Descriptor instead.
func (*CreateOptionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOptionRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *CreateOptionRequest) GetQuestionID() int32 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

func (x *CreateOptionRequest) GetOptionName() string {
	if x != nil {
		return x.OptionName
	}
	return ""
}

type CreateOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option *Option `protobuf:"bytes,1,opt,name=Option,proto3" json:"Option,omitempty"`
}

func (x *CreateOptionResponse) Reset() {
	*x = CreateOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOptionResponse) ProtoMessage() {}

func (x *CreateOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOptionResponse.ProtoReflect.Descriptor instead.
func (*CreateOptionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOptionResponse) GetOption() *Option {
	if x != nil {
		return x.Option
	}
	return nil
}

type DeleteOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteOptionRequest) Reset() {
	*x = DeleteOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOptionRequest) ProtoMessage() {}

func (x *DeleteOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteOptionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOptionRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteOptionResponse) Reset() {
	*x = DeleteOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOptionResponse) ProtoMessage() {}

func (x *DeleteOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteOptionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{7}
}

type EditOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EditOptionRequest) Reset() {
	*x = EditOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditOptionRequest) ProtoMessage() {}

func (x *EditOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditOptionRequest.ProtoReflect.Descriptor instead.
func (*EditOptionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{8}
}

func (x *EditOptionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option *Option `protobuf:"bytes,1,opt,name=Option,proto3" json:"Option,omitempty"`
}

func (x *EditOptionResponse) Reset() {
	*x = EditOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditOptionResponse) ProtoMessage() {}

func (x *EditOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditOptionResponse.ProtoReflect.Descriptor instead.
func (*EditOptionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{9}
}

func (x *EditOptionResponse) GetOption() *Option {
	if x != nil {
		return x.Option
	}
	return nil
}

type UpdateOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	QuestionID int32  `protobuf:"varint,2,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"`
	OptionName string `protobuf:"bytes,3,opt,name=OptionName,proto3" json:"OptionName,omitempty"`
	IsCorrect  bool   `protobuf:"varint,4,opt,name=IsCorrect,proto3" json:"IsCorrect,omitempty"`
}

func (x *UpdateOptionRequest) Reset() {
	*x = UpdateOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOptionRequest) ProtoMessage() {}

func (x *UpdateOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateOptionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOptionRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateOptionRequest) GetQuestionID() int32 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

func (x *UpdateOptionRequest) GetOptionName() string {
	if x != nil {
		return x.OptionName
	}
	return ""
}

func (x *UpdateOptionRequest) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type UpdateOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOptionResponse) Reset() {
	*x = UpdateOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOptionResponse) ProtoMessage() {}

func (x *UpdateOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_option_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateOptionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_option_all_proto_rawDescGZIP(), []int{11}
}

var File_quiz_gunk_v1_option_all_proto protoreflect.FileDescriptor

var file_quiz_gunk_v1_option_all_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x22, 0x87, 0x01, 0x0a, 0x06, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1d, 0x0a, 0x09,
	0x49, 0x73, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10,
	0x00, 0x18, 0x00, 0x22, 0x6d, 0x0a, 0x10, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0a,
	0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00,
	0x18, 0x00, 0x22, 0x3b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22,
	0x5e, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22,
	0x75, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e,
	0x0a, 0x0a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e,
	0x0a, 0x0a, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06,
	0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x4c, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00,
	0x10, 0x00, 0x18, 0x00, 0x22, 0x35, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x1e, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x33, 0x0a, 0x11, 0x45,
	0x64, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00,
	0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00,
	0x22, 0x4a, 0x0a, 0x12, 0x45, 0x64, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x94, 0x01, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1d, 0x0a, 0x09,
	0x49, 0x73, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10,
	0x00, 0x18, 0x00, 0x22, 0x1e, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a, 0x06, 0x08, 0x00, 0x10,
	0x00, 0x18, 0x00, 0x32, 0xcf, 0x03, 0x0a, 0x0d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x12, 0x59, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x53, 0x0a, 0x0a, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x12, 0x53, 0x0a, 0x0a, 0x45, 0x64, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x59, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x1a, 0x03, 0x88, 0x02, 0x00, 0x42, 0x37, 0x48, 0x01, 0x50, 0x00, 0x5a, 0x1c, 0x71, 0x75, 0x69,
	0x7a, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x3b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x80, 0x01, 0x00, 0x88, 0x01, 0x00, 0x90,
	0x01, 0x00, 0xb8, 0x01, 0x00, 0xd8, 0x01, 0x00, 0xf8, 0x01, 0x01, 0xd0, 0x02, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quiz_gunk_v1_option_all_proto_rawDescOnce sync.Once
	file_quiz_gunk_v1_option_all_proto_rawDescData = file_quiz_gunk_v1_option_all_proto_rawDesc
)

func file_quiz_gunk_v1_option_all_proto_rawDescGZIP() []byte {
	file_quiz_gunk_v1_option_all_proto_rawDescOnce.Do(func() {
		file_quiz_gunk_v1_option_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_quiz_gunk_v1_option_all_proto_rawDescData)
	})
	return file_quiz_gunk_v1_option_all_proto_rawDescData
}

var (
	file_quiz_gunk_v1_option_all_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
	file_quiz_gunk_v1_option_all_proto_goTypes  = []interface{}{
		(*Option)(nil),               // 0: optionpb.Option
		(*OptionFilterList)(nil),     // 1: optionpb.OptionFilterList
		(*ListOptionRequest)(nil),    // 2: optionpb.ListOptionRequest
		(*ListOptionResponse)(nil),   // 3: optionpb.ListOptionResponse
		(*CreateOptionRequest)(nil),  // 4: optionpb.CreateOptionRequest
		(*CreateOptionResponse)(nil), // 5: optionpb.CreateOptionResponse
		(*DeleteOptionRequest)(nil),  // 6: optionpb.DeleteOptionRequest
		(*DeleteOptionResponse)(nil), // 7: optionpb.DeleteOptionResponse
		(*EditOptionRequest)(nil),    // 8: optionpb.EditOptionRequest
		(*EditOptionResponse)(nil),   // 9: optionpb.EditOptionResponse
		(*UpdateOptionRequest)(nil),  // 10: optionpb.UpdateOptionRequest
		(*UpdateOptionResponse)(nil), // 11: optionpb.UpdateOptionResponse
	}
)

var file_quiz_gunk_v1_option_all_proto_depIdxs = []int32{
	0,  // 0: optionpb.OptionFilterList.TotalOption:type_name -> optionpb.Option
	1,  // 1: optionpb.ListOptionResponse.OptionFilterList:type_name -> optionpb.OptionFilterList
	0,  // 2: optionpb.CreateOptionResponse.Option:type_name -> optionpb.Option
	0,  // 3: optionpb.EditOptionResponse.Option:type_name -> optionpb.Option
	4,  // 4: optionpb.OptionService.CreateOption:input_type -> optionpb.CreateOptionRequest
	6,  // 5: optionpb.OptionService.DeleteOption:input_type -> optionpb.DeleteOptionRequest
	2,  // 6: optionpb.OptionService.ListOption:input_type -> optionpb.ListOptionRequest
	8,  // 7: optionpb.OptionService.EditOption:input_type -> optionpb.EditOptionRequest
	10, // 8: optionpb.OptionService.UpdateOption:input_type -> optionpb.UpdateOptionRequest
	5,  // 9: optionpb.OptionService.CreateOption:output_type -> optionpb.CreateOptionResponse
	7,  // 10: optionpb.OptionService.DeleteOption:output_type -> optionpb.DeleteOptionResponse
	3,  // 11: optionpb.OptionService.ListOption:output_type -> optionpb.ListOptionResponse
	9,  // 12: optionpb.OptionService.EditOption:output_type -> optionpb.EditOptionResponse
	11, // 13: optionpb.OptionService.UpdateOption:output_type -> optionpb.UpdateOptionResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_quiz_gunk_v1_option_all_proto_init() }
func file_quiz_gunk_v1_option_all_proto_init() {
	if File_quiz_gunk_v1_option_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quiz_gunk_v1_option_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionFilterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_option_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quiz_gunk_v1_option_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_gunk_v1_option_all_proto_goTypes,
		DependencyIndexes: file_quiz_gunk_v1_option_all_proto_depIdxs,
		MessageInfos:      file_quiz_gunk_v1_option_all_proto_msgTypes,
	}.Build()
	File_quiz_gunk_v1_option_all_proto = out.File
	file_quiz_gunk_v1_option_all_proto_rawDesc = nil
	file_quiz_gunk_v1_option_all_proto_goTypes = nil
	file_quiz_gunk_v1_option_all_proto_depIdxs = nil
}
