// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: quiz/gunk/v1/user_quiz/all.proto

package userquizpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID         int32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QuizQuestionID int32 `protobuf:"varint,3,opt,name=QuizQuestionID,proto3" json:"QuizQuestionID,omitempty"`
}

func (x *UserQuiz) Reset() {
	*x = UserQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQuiz) ProtoMessage() {}

func (x *UserQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQuiz.ProtoReflect.Descriptor instead.
func (*UserQuiz) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{0}
}

func (x *UserQuiz) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UserQuiz) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserQuiz) GetQuizQuestionID() int32 {
	if x != nil {
		return x.QuizQuestionID
	}
	return 0
}

type ListUserQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	Title     string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	QuizTitle string `protobuf:"bytes,5,opt,name=QuizTitle,proto3" json:"QuizTitle,omitempty"`
}

func (x *ListUserQuiz) Reset() {
	*x = ListUserQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserQuiz) ProtoMessage() {}

func (x *ListUserQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserQuiz.ProtoReflect.Descriptor instead.
func (*ListUserQuiz) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserQuiz) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ListUserQuiz) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ListUserQuiz) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListUserQuiz) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListUserQuiz) GetQuizTitle() string {
	if x != nil {
		return x.QuizTitle
	}
	return ""
}

type ListUserQuizFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalUserQuiz []*ListUserQuiz `protobuf:"bytes,1,rep,name=TotalUserQuiz,proto3" json:"TotalUserQuiz,omitempty"`
	SearchTerm    string          `protobuf:"bytes,2,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
}

func (x *ListUserQuizFilter) Reset() {
	*x = ListUserQuizFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserQuizFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserQuizFilter) ProtoMessage() {}

func (x *ListUserQuizFilter) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserQuizFilter.ProtoReflect.Descriptor instead.
func (*ListUserQuizFilter) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserQuizFilter) GetTotalUserQuiz() []*ListUserQuiz {
	if x != nil {
		return x.TotalUserQuiz
	}
	return nil
}

func (x *ListUserQuizFilter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListUserQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchTerm string `protobuf:"bytes,1,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
}

func (x *ListUserQuizRequest) Reset() {
	*x = ListUserQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserQuizRequest) ProtoMessage() {}

func (x *ListUserQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserQuizRequest.ProtoReflect.Descriptor instead.
func (*ListUserQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserQuizRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type ListUserQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListUserQuizFilter *ListUserQuizFilter `protobuf:"bytes,1,opt,name=ListUserQuizFilter,proto3" json:"ListUserQuizFilter,omitempty"`
}

func (x *ListUserQuizResponse) Reset() {
	*x = ListUserQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserQuizResponse) ProtoMessage() {}

func (x *ListUserQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserQuizResponse.ProtoReflect.Descriptor instead.
func (*ListUserQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserQuizResponse) GetListUserQuizFilter() *ListUserQuizFilter {
	if x != nil {
		return x.ListUserQuizFilter
	}
	return nil
}

type CreateUserQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID         int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QuizQuestionID int32 `protobuf:"varint,2,opt,name=QuizQuestionID,proto3" json:"QuizQuestionID,omitempty"`
}

func (x *CreateUserQuizRequest) Reset() {
	*x = CreateUserQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserQuizRequest) ProtoMessage() {}

func (x *CreateUserQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateUserQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserQuizRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateUserQuizRequest) GetQuizQuestionID() int32 {
	if x != nil {
		return x.QuizQuestionID
	}
	return 0
}

type CreateUserQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserQuiz *UserQuiz `protobuf:"bytes,1,opt,name=UserQuiz,proto3" json:"UserQuiz,omitempty"`
}

func (x *CreateUserQuizResponse) Reset() {
	*x = CreateUserQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserQuizResponse) ProtoMessage() {}

func (x *CreateUserQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserQuizResponse.ProtoReflect.Descriptor instead.
func (*CreateUserQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserQuizResponse) GetUserQuiz() *UserQuiz {
	if x != nil {
		return x.UserQuiz
	}
	return nil
}

type EditUserQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *EditUserQuizRequest) Reset() {
	*x = EditUserQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditUserQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserQuizRequest) ProtoMessage() {}

func (x *EditUserQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserQuizRequest.ProtoReflect.Descriptor instead.
func (*EditUserQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{7}
}

func (x *EditUserQuizRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type EditUserQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserQuiz *UserQuiz `protobuf:"bytes,1,opt,name=UserQuiz,proto3" json:"UserQuiz,omitempty"`
}

func (x *EditUserQuizResponse) Reset() {
	*x = EditUserQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditUserQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserQuizResponse) ProtoMessage() {}

func (x *EditUserQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserQuizResponse.ProtoReflect.Descriptor instead.
func (*EditUserQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{8}
}

func (x *EditUserQuizResponse) GetUserQuiz() *UserQuiz {
	if x != nil {
		return x.UserQuiz
	}
	return nil
}

type DeleteUserQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteUserQuizRequest) Reset() {
	*x = DeleteUserQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserQuizRequest) ProtoMessage() {}

func (x *DeleteUserQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserQuizRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserQuizRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteUserQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserQuizResponse) Reset() {
	*x = DeleteUserQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserQuizResponse) ProtoMessage() {}

func (x *DeleteUserQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserQuizResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{10}
}

type UpdateUserQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID         int32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QuizQuestionID int32 `protobuf:"varint,3,opt,name=QuizQuestionID,proto3" json:"QuizQuestionID,omitempty"`
}

func (x *UpdateUserQuizRequest) Reset() {
	*x = UpdateUserQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserQuizRequest) ProtoMessage() {}

func (x *UpdateUserQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserQuizRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserQuizRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateUserQuizRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateUserQuizRequest) GetQuizQuestionID() int32 {
	if x != nil {
		return x.QuizQuestionID
	}
	return 0
}

type UpdateUserQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateUserQuizResponse) Reset() {
	*x = UpdateUserQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserQuizResponse) ProtoMessage() {}

func (x *UpdateUserQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserQuizResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserQuizResponse) Descriptor() ([]byte, []int) {
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP(), []int{12}
}

var File_quiz_gunk_v1_user_quiz_all_proto protoreflect.FileDescriptor

var file_quiz_gunk_v1_user_quiz_all_proto_rawDesc = []byte{
	0x0a, 0x20, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x22, 0x6a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x50, 0x00, 0x12, 0x1a, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x22,
	0x0a, 0x0e, 0x51, 0x75, 0x69, 0x7a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0xab, 0x01, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x1d, 0x0a, 0x09, 0x46,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1c, 0x0a, 0x08, 0x4c, 0x61,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00,
	0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1c, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x19, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50,
	0x00, 0x12, 0x1d, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00,
	0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x79, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x3b,
	0x0a, 0x0d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1e, 0x0a, 0x0a, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10,
	0x00, 0x18, 0x00, 0x22, 0x3d, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51,
	0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00,
	0x18, 0x00, 0x22, 0x66, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75,
	0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69,
	0x7a, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x5f, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12,
	0x22, 0x0a, 0x0e, 0x51, 0x75, 0x69, 0x7a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x54, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69,
	0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75,
	0x69, 0x7a, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x42, 0x0a, 0x08,
	0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18,
	0x00, 0x22, 0x35, 0x0a, 0x13, 0x45, 0x64, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69,
	0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00,
	0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x52, 0x0a, 0x14, 0x45, 0x64, 0x69, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x37, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08,
	0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x20, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a,
	0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x77, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00,
	0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x1a, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x50, 0x00, 0x12, 0x22, 0x0a, 0x0e, 0x51, 0x75, 0x69, 0x7a, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0x08, 0x00,
	0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00,
	0x22, 0x20, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75,
	0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00,
	0x18, 0x00, 0x32, 0x83, 0x04, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71,
	0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x5d, 0x0a, 0x0c, 0x45,
	0x64, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x1f, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06,
	0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x63, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x21, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12,
	0x63, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69,
	0x7a, 0x12, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70,
	0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00,
	0x28, 0x00, 0x30, 0x00, 0x12, 0x5d, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x51, 0x75, 0x69, 0x7a, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28,
	0x00, 0x30, 0x00, 0x1a, 0x03, 0x88, 0x02, 0x00, 0x42, 0x3c, 0x48, 0x01, 0x50, 0x00, 0x5a, 0x21,
	0x71, 0x75, 0x69, 0x7a, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x71, 0x75, 0x69, 0x7a, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x71, 0x75, 0x69, 0x7a, 0x70,
	0x62, 0x80, 0x01, 0x00, 0x88, 0x01, 0x00, 0x90, 0x01, 0x00, 0xb8, 0x01, 0x00, 0xd8, 0x01, 0x00,
	0xf8, 0x01, 0x01, 0xd0, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quiz_gunk_v1_user_quiz_all_proto_rawDescOnce sync.Once
	file_quiz_gunk_v1_user_quiz_all_proto_rawDescData = file_quiz_gunk_v1_user_quiz_all_proto_rawDesc
)

func file_quiz_gunk_v1_user_quiz_all_proto_rawDescGZIP() []byte {
	file_quiz_gunk_v1_user_quiz_all_proto_rawDescOnce.Do(func() {
		file_quiz_gunk_v1_user_quiz_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_quiz_gunk_v1_user_quiz_all_proto_rawDescData)
	})
	return file_quiz_gunk_v1_user_quiz_all_proto_rawDescData
}

var (
	file_quiz_gunk_v1_user_quiz_all_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
	file_quiz_gunk_v1_user_quiz_all_proto_goTypes  = []interface{}{
		(*UserQuiz)(nil),               // 0: userquizpb.UserQuiz
		(*ListUserQuiz)(nil),           // 1: userquizpb.ListUserQuiz
		(*ListUserQuizFilter)(nil),     // 2: userquizpb.ListUserQuizFilter
		(*ListUserQuizRequest)(nil),    // 3: userquizpb.ListUserQuizRequest
		(*ListUserQuizResponse)(nil),   // 4: userquizpb.ListUserQuizResponse
		(*CreateUserQuizRequest)(nil),  // 5: userquizpb.CreateUserQuizRequest
		(*CreateUserQuizResponse)(nil), // 6: userquizpb.CreateUserQuizResponse
		(*EditUserQuizRequest)(nil),    // 7: userquizpb.EditUserQuizRequest
		(*EditUserQuizResponse)(nil),   // 8: userquizpb.EditUserQuizResponse
		(*DeleteUserQuizRequest)(nil),  // 9: userquizpb.DeleteUserQuizRequest
		(*DeleteUserQuizResponse)(nil), // 10: userquizpb.DeleteUserQuizResponse
		(*UpdateUserQuizRequest)(nil),  // 11: userquizpb.UpdateUserQuizRequest
		(*UpdateUserQuizResponse)(nil), // 12: userquizpb.UpdateUserQuizResponse
	}
)

var file_quiz_gunk_v1_user_quiz_all_proto_depIdxs = []int32{
	1,  // 0: userquizpb.ListUserQuizFilter.TotalUserQuiz:type_name -> userquizpb.ListUserQuiz
	2,  // 1: userquizpb.ListUserQuizResponse.ListUserQuizFilter:type_name -> userquizpb.ListUserQuizFilter
	0,  // 2: userquizpb.CreateUserQuizResponse.UserQuiz:type_name -> userquizpb.UserQuiz
	0,  // 3: userquizpb.EditUserQuizResponse.UserQuiz:type_name -> userquizpb.UserQuiz
	5,  // 4: userquizpb.UserQuizService.CreateUserQuiz:input_type -> userquizpb.CreateUserQuizRequest
	7,  // 5: userquizpb.UserQuizService.EditUserQuiz:input_type -> userquizpb.EditUserQuizRequest
	9,  // 6: userquizpb.UserQuizService.DeleteUserQuiz:input_type -> userquizpb.DeleteUserQuizRequest
	11, // 7: userquizpb.UserQuizService.UpdateUserQuiz:input_type -> userquizpb.UpdateUserQuizRequest
	3,  // 8: userquizpb.UserQuizService.ListUserQuiz:input_type -> userquizpb.ListUserQuizRequest
	6,  // 9: userquizpb.UserQuizService.CreateUserQuiz:output_type -> userquizpb.CreateUserQuizResponse
	8,  // 10: userquizpb.UserQuizService.EditUserQuiz:output_type -> userquizpb.EditUserQuizResponse
	10, // 11: userquizpb.UserQuizService.DeleteUserQuiz:output_type -> userquizpb.DeleteUserQuizResponse
	12, // 12: userquizpb.UserQuizService.UpdateUserQuiz:output_type -> userquizpb.UpdateUserQuizResponse
	4,  // 13: userquizpb.UserQuizService.ListUserQuiz:output_type -> userquizpb.ListUserQuizResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_quiz_gunk_v1_user_quiz_all_proto_init() }
func file_quiz_gunk_v1_user_quiz_all_proto_init() {
	if File_quiz_gunk_v1_user_quiz_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserQuizFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditUserQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditUserQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quiz_gunk_v1_user_quiz_all_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quiz_gunk_v1_user_quiz_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_gunk_v1_user_quiz_all_proto_goTypes,
		DependencyIndexes: file_quiz_gunk_v1_user_quiz_all_proto_depIdxs,
		MessageInfos:      file_quiz_gunk_v1_user_quiz_all_proto_msgTypes,
	}.Build()
	File_quiz_gunk_v1_user_quiz_all_proto = out.File
	file_quiz_gunk_v1_user_quiz_all_proto_rawDesc = nil
	file_quiz_gunk_v1_user_quiz_all_proto_goTypes = nil
	file_quiz_gunk_v1_user_quiz_all_proto_depIdxs = nil
}
